#!/usr/bin/env python3
"""LaTeX tables + inline-number macros from the tidy CSVs -> paper/tables/.

Outputs:
  status.tex      \\ifprovisional toggle + fleet status line (draft banner)
  headline.tex    median (min-max; n) final scores, env x N x dropout
  signtests.tex   pre-registered contrasts: seed pairs + config-level sign tests
  prospective.tex Spearman rho(sharp@t, final) at probe checkpoints, LOCO range
  tps.tex         TPS dose-response summary (distribution stats, never paired)
  replication.tex April-vs-June cross-era check (appendix)
  numbers.tex     \\newcommand macros for every number cited inline in the text;
                  missing values render as a visible red [pending] marker.

Honesty contract: every number is computed from runs.csv/timeseries.csv at
build time. Nothing is hand-entered. Missing data -> \\pendingnum, never a
guess.
"""
import datetime
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rlpd_common import (PAPER_TABLES, TIDY, dropout_pairs, mannwhitney,
                         sign_test, spearman_loco)

ENVS = ["pen-binary-v0", "door-binary-v0"]
ENV_SHORT = {"pen-binary-v0": "pen", "door-binary-v0": "door"}
LAST_WINDOW = 800000
PEND = r"\pendingnum{}"


def fmt_band(vals):
    v = pd.Series(vals).dropna()
    if v.empty:
        return PEND
    if len(v) == 1:
        return f"{v.iloc[0]:.2f} \\textsuperscript{{(n=1)}}"
    return f"{v.median():.2f} ({v.min():.2f}--{v.max():.2f}; n={len(v)})"


def fmt_p(p):
    if pd.isna(p):
        return PEND
    return f"{p:.3f}" if p >= 0.001 else "$<$0.001"


def macro(name, value):
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


# ----------------------------------------------------------------- status
def write_status(prog):
    today = datetime.date.today().isoformat()
    complete = prog["complete"]
    # Single source: compose the banner line from the same macros numbers.tex
    # defines, so the two files cannot drift.
    line = ("main fleet \\FleetMainDone/\\FleetMainTotal{} done, "
            "TPS arm \\FleetTpsDone/\\FleetTpsTotal{} done "
            f"(synced {today})")
    txt = ("% AUTO-GENERATED by analysis/make_tables.py -- do not edit\n"
           "\\newif\\ifprovisional\n"
           + ("\\provisionalfalse\n" if complete else "\\provisionaltrue\n")
           + macro("fleetstatusline", line)
           # \prov{...}: marks a hand-written RESULTS-TENSE sentence whose
           # truth depends on the full fleet. Renders a red dagger while
           # provisional; renders nothing once the fleet is complete.
           # At finalize: grep '\\prov{' in main.tex and verify each claim
           # against the regenerated tables before removing the wrapper.
           + ("\\newcommand{\\prov}[1]{#1}\n" if complete else
              "\\newcommand{\\prov}[1]{#1\\textsuperscript{"
              "\\textcolor{red}{$\\dagger$}}}\n"))
    (PAPER_TABLES / "status.tex").write_text(txt)
    print(f"  status.tex: main {prog['main_done']}/{prog['main_total']}, "
          f"tps {prog['tps_done']}/{prog['tps_total']}, "
          f"complete={complete}")


# ----------------------------------------------------------------- headline
def write_headline(runs, macros):
    r = runs[(runs["era"] == "washu") & (runs["status"] == "done")
             & (runs["tps"] == 0)]
    lines = [
        "% AUTO-GENERATED by analysis/make_tables.py -- do not edit by hand",
        "\\begin{tabular}{llccc}", "\\toprule",
        "env & $N$ & no dropout & dropout $p$=0.01 & $\\Delta$ (median) \\\\",
        "\\midrule",
    ]
    name_map = {("pen-binary-v0", 2): "PenNTwo", ("pen-binary-v0", 10): "PenNTen",
                ("door-binary-v0", 2): "DoorNTwo", ("door-binary-v0", 10): "DoorNTen"}
    # Emit EVERY designed config; a never-run cell must render \pendingnum,
    # never be silently absent (honesty contract, analysis/README.md).
    for env in ENVS:
        for nq in (2, 4, 6, 10):
            g = r[(r["env"] == env) & (r["nq"] == nq) & (r["mq"] == 2)]
            a = g[g["drop"] == 0.0]["final_frac"]
            b = g[g["drop"] == 0.01]["final_frac"]
            delta = (f"{b.median() - a.median():+.2f}"
                     if len(a.dropna()) >= 2 and len(b.dropna()) >= 2 else PEND)
            lines.append(f"{ENV_SHORT[env]} & {nq} & {fmt_band(a)} & "
                         f"{fmt_band(b)} & {delta} \\\\")
            if (env, nq) in name_map:
                base = name_map[(env, nq)]
                macros.append(macro(base + "NoDrop", fmt_band(a)))
                macros.append(macro(base + "Drop", fmt_band(b)))
                macros.append(macro(base + "Delta", delta))
        # pen M=1 ablation arms (both designed: p in {0, 0.01})
        if env == "pen-binary-v0":
            g1 = r[(r["env"] == env) & (r["nq"] == 2) & (r["mq"] == 1)]
            a1 = g1[g1["drop"] == 0.0]["final_frac"]
            b1 = g1[g1["drop"] == 0.01]["final_frac"]
            d1 = (f"{b1.median() - a1.median():+.2f}"
                  if len(a1.dropna()) >= 2 and len(b1.dropna()) >= 2 else PEND)
            lines.append(f"pen ($M$=1) & 2 & {fmt_band(a1)} & "
                         f"{fmt_band(b1)} & {d1} \\\\")
            macros.append(macro("PenMOneNoDrop", fmt_band(a1)))
            macros.append(macro("PenMOneDrop", fmt_band(b1)))
        lines.append("\\midrule" if env == ENVS[0] else "\\bottomrule")
    lines.append("\\end{tabular}")
    (PAPER_TABLES / "headline.tex").write_text("\n".join(lines) + "\n")
    print(f"  headline.tex: {len(r)} done runs")


# ----------------------------------------------------------------- sign tests
def write_signtests(runs, macros):
    pairs = dropout_pairs(runs)  # seed-paired dropout contrasts, mq=2
    lines = [
        "% AUTO-GENERATED by analysis/make_tables.py",
        "\\begin{tabular}{lccc}", "\\toprule",
        "contrast & positive / pairs & config directions & sign-test $p$ \\\\",
        "\\midrule",
    ]
    # (a) dropout effect, seed-level pairs per env
    for env in ENVS:
        p_env = pairs[pairs["env"] == env]
        if p_env.empty:
            lines.append(f"dropout $>$ none ({ENV_SHORT[env]}) & {PEND} & {PEND} & {PEND} \\\\")
            continue
        npos = int((p_env["delta"] > 0).sum())
        ntot = len(p_env)
        cfg = p_env.groupby("nq")["delta"].median()
        cpos, ctot = int((cfg > 0).sum()), len(cfg)
        p = sign_test(npos, ntot)
        lines.append(f"dropout $>$ none ({ENV_SHORT[env]}) & {npos}/{ntot} & "
                     f"{cpos}/{ctot} $N$-configs & {fmt_p(p)} \\\\")
        if env == "pen-binary-v0":
            macros += [macro("DropPairsPosPen", f"{npos}/{ntot}"),
                       macro("DropSignPPen", fmt_p(p))]
        else:
            macros += [macro("DropPairsPosDoor", f"{npos}/{ntot}"),
                       macro("DropSignPDoor", fmt_p(p))]
    # (b) dropout effect at N=2 vs at N=10 (the interaction claim), pen
    for nq, mname in ((2, "DropDeltaPenNTwo"), (10, "DropDeltaPenNTen")):
        d = pairs[(pairs["env"] == "pen-binary-v0") & (pairs["nq"] == nq)]["delta"]
        macros.append(macro(mname, fmt_band(d)))
        lines.append(f"dropout $\\Delta$ at $N$={nq} (pen) & "
                     f"{fmt_band(d)} & & \\\\")
    # (c) N=10 > N=2, no dropout: DESCRIPTIVE concordance only. The
    # pre-registered discipline reserves seed-level paired TESTS for dropout
    # contrasts (rule 3); this row reports counts without a p-value.
    r = runs[(runs["era"] == "washu") & (runs["status"] == "done")
             & (runs["mq"] == 2) & (runs["tps"] == 0) & (runs["drop"] == 0.0)]
    piv = r.pivot_table(index=["env", "seed"], columns="nq",
                        values="final_frac")
    if {2, 10} <= set(piv.columns):
        piv2 = piv.dropna(subset=[2, 10])
        npos = int((piv2[10] > piv2[2]).sum())
        ntot = len(piv2)
        lines.append(f"$N$=10 $>$ $N$=2 (no drop, both envs) & {npos}/{ntot} & "
                     f"\\multicolumn{{2}}{{c}}{{descriptive (no test "
                     f"pre-registered)}} \\\\")
        macros += [macro("NEffectPairs", f"{npos}/{ntot}")]
    else:
        macros += [macro("NEffectPairs", PEND)]
    lines += ["\\bottomrule", "\\end{tabular}"]
    (PAPER_TABLES / "signtests.tex").write_text("\n".join(lines) + "\n")
    print(f"  signtests.tex: {len(pairs)} dropout pairs")


# ----------------------------------------------------------------- prospective
def final_sharp(ts, col="sharp_s005"):
    probes = ts[ts[col].notna() & (ts["step"] > LAST_WINDOW)]
    return (probes.groupby(["env", "nq", "mq", "drop", "tps", "seed"])[col]
            .median().rename("final_sharp").reset_index())


def write_prospective(ts, runs, macros):
    keys = ["env", "nq", "mq", "drop", "tps", "seed"]
    done = runs[(runs["era"] == "washu") & (runs["status"] == "done")
                & (runs["tps"] == 0) & (runs["env"] == "pen-binary-v0")]
    probes = ts[(ts["env"] == "pen-binary-v0") & (ts["tps"] == 0)
                & ts["sharp_s005"].notna()]
    lines = ["% AUTO-GENERATED by analysis/make_tables.py",
             "\\begin{tabular}{lcccc}", "\\toprule",
             "probe step & $\\rho_s$ (all) & LOCO range & "
             "$\\rho_s$ (excl. $M$=1) & $n$ runs \\\\", "\\midrule"]
    merged = probes.merge(done[keys + ["final_frac"]], on=keys)
    wrote_any = False
    for t_step in (50000, 100000, 200000, 500000):
        d = merged[merged["step"] == t_step]
        if len(d) < 6:
            lines.append(f"{t_step//1000}k & {PEND} & & & \\\\")
            continue
        wrote_any = True
        st = spearman_loco(d, "sharp_s005", "final_frac", ["nq", "mq", "drop"])
        d2 = d[d["mq"] != 1]
        st2 = spearman_loco(d2, "sharp_s005", "final_frac", ["nq", "drop"])
        lines.append(
            f"{t_step//1000}k & {st['rho']:.2f} & "
            f"[{st['loco_lo']:.2f}, {st['loco_hi']:.2f}] & "
            f"{st2['rho']:.2f} & {st['n']} \\\\")
        if t_step == 100000:
            macros += [macro("ProspectiveRho", f"{st['rho']:.2f}"),
                       macro("ProspectiveLoco",
                             f"[{st['loco_lo']:.2f}, {st['loco_hi']:.2f}]"),
                       macro("ProspectiveN", str(st["n"])),
                       macro("ProspectiveRhoExclM", f"{st2['rho']:.2f}")]
    if not wrote_any:
        macros += [macro("ProspectiveRho", PEND), macro("ProspectiveLoco", PEND),
                   macro("ProspectiveN", PEND), macro("ProspectiveRhoExclM", PEND)]
    lines += ["\\bottomrule", "\\end{tabular}"]
    (PAPER_TABLES / "prospective.tex").write_text("\n".join(lines) + "\n")
    # final-sharpness <-> final-score association macros (Fig 3b text)
    fs = final_sharp(ts).merge(done, on=keys)
    st = spearman_loco(fs.dropna(subset=["final_sharp", "final_frac"]),
                       "final_sharp", "final_frac", ["nq", "mq", "drop"])
    macros += [macro("SharpRho", f"{st['rho']:.2f}" if pd.notna(st["rho"]) else PEND),
               macro("SharpRhoN", str(st["n"])),
               macro("SharpLoco",
                     f"[{st['loco_lo']:.2f}, {st['loco_hi']:.2f}]"
                     if pd.notna(st["loco_lo"]) else PEND)]
    print(f"  prospective.tex: merged probe rows={len(merged)}")


# ----------------------------------------------------------------- tps
def write_tps(runs, macros):
    r = runs[(runs["era"] == "washu") & (runs["status"] == "done")
             & (runs["mq"] == 2) & (runs["drop"] == 0.0)]
    lines = ["% AUTO-GENERATED by analysis/make_tables.py",
             "\\begin{tabular}{llcccc}", "\\toprule",
             "env & $N$ & $\\sigma_{TPS}$=0 & 0.1 & 0.2 & 0.3 \\\\",
             "\\midrule"]
    have_tps = (r["tps"] > 0).any()
    for env in ENVS:
        for nq in (2, 10):
            cells = []
            base = r[(r["env"] == env) & (r["nq"] == nq) & (r["tps"] == 0)]["final_frac"]
            for s in (0.0, 0.1, 0.2, 0.3):
                g = r[(r["env"] == env) & (r["nq"] == nq)
                      & (r["tps"] == s)]["final_frac"]
                if env == "door-binary-v0" and s in (0.1, 0.3):
                    cells.append("--")  # not in the design
                else:
                    cells.append(fmt_band(g))
            lines.append(f"{ENV_SHORT[env]} & {nq} & " + " & ".join(cells) + " \\\\")
            if env == "pen-binary-v0" and have_tps:
                g2 = r[(r["env"] == env) & (r["nq"] == nq) & (r["tps"] == 0.2)]["final_frac"]
                mw = mannwhitney(base, g2)
                macros.append(macro(f"TpsMWPenN{'Two' if nq == 2 else 'Ten'}",
                                    fmt_p(mw)))
    if not have_tps:
        macros += [macro("TpsMWPenNTwo", PEND), macro("TpsMWPenNTen", PEND)]
        lines.append("\\multicolumn{6}{l}{\\emph{TPS arm (78877) pending "
                     "-- distribution comparison only, never seed-paired}} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (PAPER_TABLES / "tps.tex").write_text("\n".join(lines) + "\n")
    print(f"  tps.tex: tps runs done={int((r['tps'] > 0).sum())}")


# ----------------------------------------------------------------- replication
def write_replication(runs):
    """April (single-seed era) vs June medians, claim-bearing pen configs."""
    lines = ["% AUTO-GENERATED by analysis/make_tables.py",
             "\\begin{tabular}{lccc}", "\\toprule",
             "config (pen) & April (n=1 era) & June fleet & consistent? \\\\",
             "\\midrule"]
    apr = runs[(runs["era"] == "april") & (runs["status"] == "done")
               & (runs["env"] == "pen-binary-v0")]
    jun = runs[(runs["era"] == "washu") & (runs["status"] == "done")
               & (runs["env"] == "pen-binary-v0") & (runs["tps"] == 0)]
    for nq, mq, drop in ((2, 2, 0.0), (4, 2, 0.0), (6, 2, 0.0), (10, 2, 0.0),
                         (2, 2, 0.01), (10, 2, 0.01), (2, 1, 0.0)):
        a = apr[(apr["nq"] == nq) & (apr["mq"] == mq)
                & (apr["drop"] == drop) & (apr["seed"] == 0)]["final_frac"]
        j = jun[(jun["nq"] == nq) & (jun["mq"] == mq)
                & (jun["drop"] == drop)]["final_frac"]
        a_s = f"{a.iloc[0]:.2f}" if len(a) else "--"
        j_s = fmt_band(j)
        if len(a) and len(j.dropna()) >= 2:
            ok = ("\\checkmark" if j.min() - 0.08 <= a.iloc[0] <= j.max() + 0.08
                  else "see text")
        elif len(a):
            ok = PEND  # June side not yet multi-seed: undetermined, not blank
        else:
            ok = "--"  # config not in the April grid
        lines.append(f"$N$={nq}, $M$={mq}, $p$={drop} & {a_s} & {j_s} & {ok} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (PAPER_TABLES / "replication.tex").write_text("\n".join(lines) + "\n")
    print("  replication.tex written")


def main():
    PAPER_TABLES.mkdir(parents=True, exist_ok=True)
    runs = pd.read_csv(TIDY / "runs.csv")
    ts = pd.read_csv(TIDY / "timeseries.csv")
    prog = json.loads((TIDY / "progress.json").read_text())

    macros = ["% AUTO-GENERATED by analysis/make_tables.py -- inline numbers\n",
              "\\newcommand{\\pendingnum}{\\textbf{\\textcolor{red}{[pending]}}}\n",
              macro("FleetMainDone", prog["main_done"]),
              macro("FleetMainTotal", prog["main_total"]),
              macro("FleetTpsDone", prog["tps_done"]),
              macro("FleetTpsTotal", prog["tps_total"])]
    print("tables:")
    write_status(prog)
    write_headline(runs, macros)
    write_signtests(runs, macros)
    write_prospective(ts, runs, macros)
    write_tps(runs, macros)
    write_replication(runs)
    (PAPER_TABLES / "numbers.tex").write_text("".join(macros))
    print(f"  numbers.tex: {len(macros)} macros")


if __name__ == "__main__":
    main()
